### ISSUE TITLE
how to do something once upload finished?

### ISSUE THREAD

**Issue by martinleopold** [morris/vinyl-ftp#30]
this may be a noob questions, so please be gentle :)

it seems that .dest() emits files immediately, which is certainly preferred in some cases.
I want to trigger a browsersync reload once the upload is complete (once per file, or once per stream)

**Comment by morris** [comment]
Files are only emitted once they are transferred completely. If you want to call a function when all files are uploaded, `dest()` returns a stream, so you could do `dest( ... ).on( 'end', function () { reloadHere() } );` - is that what you're looking for?

**Comment by ingro** [comment]
Thanks for your tip, the `end` event on the stream works fine when the upload is successfull, but what can I do to detect the end of un upload that fails, like if the ftp server reject my login? I see in the log the login error, but the stream didn't emit neither and `end` nor a `error` event.

**Comment by morris** [comment]
The problem here ist that emitting `error` events always brings down the entire stream. That is not desired in cases of 'Too many connections' and other, recoverable errors. So throughout vinyl-ftp, I decided not to emit any error events at all. Of course, responding to errors (recoverable or not) would also be handy and is planned for the next release.

'Login incorrect' should probably emit a regular error event, as the whole stream is defunct in that case. For recovarable errors, I'm planning to emit a `warning` event instead which can be responded to without without bringing down the entire stream.

In any case, it's a bug that none of `end`, `finish`, or `error` is emitted because it should finish somehow. Thanks for your input, I hope to fix this soon :-)

**Comment by martinleopold** [comment]
> is that what you're looking for?
thanks @morris, that solves my case.

**Comment by ingro** [comment]
Thanks for your comprehensive reply, now it's all clearer. I'm waiting for a fix so, I need it cause I'm wrapping the process of uploading via ftp behind an api call, and actually it hangs when some non-recoverable error happens.

Thanks again and keep up the good work!

**Comment by morris** [comment]
The 'warning' system is not ready yet, but login errors are now properly reported. Thanks for your input :-)

**Comment by ingro** [comment]
Awesome, I will test it out, thanks for the fast fix! :)
