### ISSUE TITLE
'newer' only works every other time

### ISSUE THREAD

**Issue by designrubenz** [morris/vinyl-ftp#32]
I tried everything I could think of and googled a lot, but I cannot solve this issue:
The file index.html gets uploaded only every other time, regardless whether it has been changed or not.
This seems to affect files in the root-directory only.

![ftp-vinyl](https://cloud.githubusercontent.com/assets/5677554/9758696/83e680f8-56e8-11e5-8753-89717de30be8.gif)

I highlighted the MLSD-command, because this might be a clue: the root is only listed every other time.

Any help would be greatly appreciated!

**Comment by morris** [comment]
My first guess is that your `prod` task only touches the file mtime every other time; `newer` only compares mtimes. Please paste the complete gulp file (don't screenshot) so I can debug easily.

**Comment by designrubenz** [comment]
@morris wow, thank you for the instant response. 
You'll find my gulpfile here: https://github.com/designrubenz/jsidiots-gulpfile/blob/master/gulpfile.js

**Comment by morris** [comment]
Since you're always copying index.html to `./build`, it should actually upload every time, because the mtime should have changed. What happens if you remove the `prod` dependency?

**Comment by morris** [comment]
Oh, now I see what's going on. Your production task finishes *before* the gulp stream chain(s) are done, because you don't return any stream from the task. You should split up the production task into seperate tasks with one `return gulp.src( ... ).pipe( ... );`, then use them as dependencies in your production task. Otherwise gulp will execute `deploy` before `prod` is done.

**Comment by designrubenz** [comment]
@morris So, to sum up, the issue had nothing to do with your vinyl-ftp-code and you were nevertheless debugging my gulpfile! How can I thank you? It would have impossible for me to solve this myself. Can I send beer to Kiel? ;-) Thanks man, I'm so grateful and really impressed by your generosity!

PS I will upload my edited gulpfile any minute...

**Comment by morris** [comment]
Can't say no to free beer :-) no problem, I never actually ran your gulp file; just saw the error because it's not uncommon. As a side note, these kind of questions are better off at Stack Overflow so others can find them as well. Only if you're sure that it's a bug in a library you should create a GitHub issue. Cheers!

**Comment by designrubenz** [comment]
Lessons learned! Thank you!
